version: '3.7'

services:
 
  cargoeye_plm:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8001:8001"
      # - "5437:5437"
    environment:
      - MONGO_IP=192.168.0.9
      - STORAGE_ACC_NAME=cgeplmtest
      - STORAGE_ACC_KEY=7IKUE6/bIZkpX+nGMOfCxn703kDkd1sKmH2Xp+afqH23+fZLyS1ZCdFPoTO52Xtb2PN7KlTtDBMw+ASt5NaEHQ==
      - STORAGE_CON_STR=DefaultEndpointsProtocol=https;AccountName=cgeplmtest;AccountKey=7IKUE6/bIZkpX+nGMOfCxn703kDkd1sKmH2Xp+afqH23+fZLyS1ZCdFPoTO52Xtb2PN7KlTtDBMw+ASt5NaEHQ==;EndpointSuffix=core.windows.net
      - PLM_DB_USERNAME=user
      - PLM_DB_PASSWORD=password
      - PLM_DB_DATABASE=cargoeye-inventory
      - PLM_DB_HOST=192.168.0.9
      - PLM_DB_PORT=27017
      - PLM_COLLECTION=commissions​
      - IS_CLOUD=
      - CLOUD_DB_USERNAME=cgeplmcosmosdev
      - CLOUD_DB_PASSWORD=X5CLt3vRtZ9DM8QaKzAOz6qBYXIRClTCW3KKtcCNYpyfe7dOTR0IIEfwZRWKtAqsFsAUIfRCQqRcgqny28Xquw==
      - CLOUD_DB_DATABASE=cargoeye-inventory
      - CLOUD_DB_HOST=cgeplmcosmosdev.mongo.cosmos.azure.com
      - CLOUD_DB_PORT=10255
    depends_on:
      - plm_db_local
  
  plm_db_local:
    image: mongo:4.0.0
    container_name: plm_db_local
    restart: always
    volumes:
      - /plm_local_db/:/data/db
      - /config/computer:/config/computer
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_DATABASE=cargodetails
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27018:27017
   